### PR TITLE
fix: removed black border for tasks page

### PR DESCRIPTION
**Pull request by ceelo777**
Nice to meet you all - removed the black border for the tasks page - let me know if you guys want it removed for every page.

fixes #96

### CODE REVIEW

**Comment by whyDontI** [comment]
Hi @ceelo777 Thanks for the PR 😄 
Can you put some screenshots in the description? It'll be easier to review 👍🏽

**Comment by ceelo777** [comment]
How do I add a task? Right now, it says "No Tasks Found."

**Comment by akankshadharkar** [comment]
Hi @ceelo777 
Nice to meet you! 
Would you like to be a part of our discord channel? That is where we discuss features and tasks, etc
We also play amongUs sometimes 😛 
If you'd like to join, just use this link - https://discord.gg/Jr6w6nUD

**Comment by akankshadharkar** [comment]
> How do I add a task? Right now, it says "No Tasks Found."

**Comment by akankshadharkar** [comment]
Once this

**Comment by akankshadharkar** [comment]
My bad, guys
I was doing something and accidentally clicked that

**Review by ankushdharkar — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
