### PR TITLE
add loading skeleton for user profile in the navbar

### PR DESCRIPTION
**Pull request by AnujChhikara**
Date: 8 Oct, 2024

Developer Name: Anuj Chhikara

---

## Issue Ticket Number

#1268
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Problem Screenshot</summary>

brave_VlbdjZOzyw
</details>
<details>
<summary>Solved Screenshot</summary>

brave_ZK8h0rXuVS
</details>

<details>
<summary>Test Coverage</summary>

Earlier coverage
image

Now coverage

image

image

 Test Results: All tests passed successfully (7/7) for the Navbar component.
</details>

## Additional Notes

- **Problem**: When navigating the navbar, the user status briefly displays "Login with GitHub" before showing the user data, leading to a confusing experience for users.

- **Fix**: Implemented a loading skeleton to provide a visual indication while the user data is being fetched, ensuring a smoother transition and a clearer user experience.

- **Impact**: This enhancement reduces confusion and improves the overall user experience by clearly indicating that the application is loading user data.

### CODE REVIEW

**Comment by vinit717** [comment]
Your Github action is failing  fix that

**Comment by AnujChhikara** [comment]
> Your Github action is failing fix that

Hi Vinit, sorry that i don't tested the test result properly. The test that my code is failing is not written properly like the description of the test is himself misleading. Can i also rewrite that test??

**Comment by vinit717** [comment]
Please add the test coverage of the file you have changed

**Comment by AnujChhikara** [comment]
Sorry, I forgot about that. Test coverage of Navbar added now

**Review by yesyash — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Pull request merged**
