### PR TITLE
added responsiveness to the in-review page

### PR DESCRIPTION
**Pull request by Amandixit10**
### Description:

The card have min width of 267px because of the content inside it, like progress bar. Also the select have with 20em changed it to 100%. Now the navbar is not detaching for screen size of iPhone 4 or less. 

### Dev Tested:
- [x] Yes

### Images/video of the change:

https://github.com/Real-Dev-Squad/website-status/assets/55151241/2684caff-98b2-4d8f-ab0e-7dc13609661d

### CODE REVIEW

**Comment by shubhamsigdar1** [comment]
> Issue:

Please link issue ticket in description

**Comment by Amandixit10** [comment]
I have linked the issue ticket in the description.

**Review by shubhamsigdar1 — COMMENTED** [review]
great work @Amandixit10, Just make one video and attach in description 
in which you click on all tab and showing responsiveness. Just like I maked for you in issue ticket

**Comment by Amandixit10** [comment]
https://github.com/Real-Dev-Squad/website-status/assets/55151241/b8358235-f4d2-4793-b389-76177d97b4da

The vedio showcase the responsiveness of different task tabs below 370px, for which earlier the navbar got detach from the body for width <=370px.

**Comment by Amandixit10** [comment]
@shubhamsigdar1 please review it.

**Review by shubhamsigdar1 — APPROVED** [review]

**Review by sahsisunny — APPROVED** [review]

**Pull request merged**
