### PR TITLE
chore: remove updateCardContent & use the RTK hook

### PR DESCRIPTION
**Pull request by bhtibrewal**
### Issue:
- #678

### Description:
remove util updateCardContent and use RTK instead

### Anything you would like to inform the reviewer about:
just a small cleanup PR

### Dev Tested:
- [x] Yes

### Images/video of the change:
image

image

### CODE REVIEW

**Review by vinit717 — DISMISSED** [review]

**Review by bharati-21 — CHANGES_REQUESTED** [review]
Please add test cases for the changes.

**Review by vinit717 — DISMISSED** [review]

**Review by bharati-21 — APPROVED** [review]
LGTM

**Review by iamitprakash — CHANGES_REQUESTED** [review]
test coverage stats

**Review by bharati-21 — DISMISSED** [review]
LGTM

**Review by bharati-21 — DISMISSED** [review]
LGTM

**Review by DashDeipayan — APPROVED** [review]
LGTM

**Pull request merged**
