### PR TITLE
Add Typescript prop types validations and mobile responsive

### PR DESCRIPTION
**Pull request by sumitd94**
This PR includes the following changes

1. Renamed all the files to `.tsx` extension
2. Added the prop types validations as per `typescript` rules
3. Improved the font size, and layouts of the cards.
4. The screen is now mobile responsive (Please check the below screenshots for the same)

## Portrait Mode

image

image

## Landscape Mode

image

### CODE REVIEW

**Comment by whyDontI** [comment]
Everything looks Great 🔥 
NIT: If you can make the corners a bit rounded as shown in the reference picture, it'll be great.

***

**Review by whyDontI — CHANGES_REQUESTED** [review]
Everything looks Great 🔥 
NIT: If you can make the corners a bit rounded as shown in the reference picture, it'll be great.

***

**Comment by sumitd94** [comment]
> Everything looks Great 
> NIT: If you can make the corners a bit rounded as shown in the reference picture, it'll be great.
> 
> 

Done, Please check

image

**Review by whyDontI — APPROVED** [review]
Thanks @sumitd94 👍🏽

**Review by ankushdharkar — APPROVED** [review]

**Pull request merged**
