### PR TITLE
REFACTOR: removed old see more button from TaskList components

### PR DESCRIPTION
**Pull request by sahsisunny**
### Description:
In this PR, I removed the old see more button functionality from the TaskList components. This was done because the new Load More button functionality is now in place.

### Anthing you would like to inform the reviewer about:
Also, fix the typo in the PR template.

### Dev Tested:
- [x] Yes

### Test Coverage
image

### CODE REVIEW

**Comment by harshith-venkatesh** [comment]
Can you look into improving test coverage here

**Comment by sahsisunny** [comment]
> Can you look into improving test coverage here

Apologies, but I'm currently unable to write tests for this component. Could you kindly assist me in improving test coverage?

**Comment by harshith-venkatesh** [comment]
Could you please refer other test cases in project and try creating test cases, it seems like you have removed the scenarios, you could have tested by modifying them as well.

**Review by Pratiyushkumar — DISMISSED** [review]
LGTM

**Comment by sahsisunny** [comment]
I am unable to write the test for lines 23 to 24 of the `TaskList.tsx` component, so I have decided to close this PR.

**Comment by harshith-venkatesh** [comment]
Why are we closing the PR here

**Comment by sahsisunny** [comment]
> Why are we closing the PR here

https://github.com/Real-Dev-Squad/website-status/pull/772#issuecomment-1656429993

**Review by Pratiyushkumar — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Review by Pratiyushkumar — APPROVED** [review]

**Pull request merged**
