### PR TITLE
Progress update component

### PR DESCRIPTION
**Pull request by fakhruddinkw**
### Issue:
#845 

### Description:
As per the RFC #855 , moving forward with the modal view of the progress updates

**WORKING VIDEO**

[ProgressDetails_Working.webm](https://github.com/Real-Dev-Squad/website-status/assets/85249044/117cb330-3265-404d-89ab-085591be2d32)

**UPDATED**

[updated_progress_details.webm](https://github.com/Real-Dev-Squad/website-status/assets/85249044/0198f1f0-f41b-4ef3-a8b2-440ba2947330)

**RESPONSIVENESS**

[Responsiveness.webm](https://github.com/Real-Dev-Squad/website-status/assets/85249044/f0d377f6-e3f2-4637-ab4e-6d5e699315f4)

**TEST COVERAGE**
ProgressDetails
coverage

### CODE REVIEW

**Review by iamitprakash — APPROVED** [review]

**Comment by shubhamsigdar1** [comment]
Nit: Hello @fakhruddinkw, you've done excellent work! Could you please enhance the appearance of an item in a list to make it look clickable?
image

**Comment by fakhruddinkw** [comment]
> Nit: Hello @fakhruddinkw, you've done excellent work! Could you please enhance the appearance of an item in a list to make it look clickable? image

What do you suggest?

**Comment by shubhamsigdar1** [comment]
> What do you suggest?

I suggest adding a subtle hover effect to the list item, such as changing its background color or underlining the text when someone hovers their mouse pointer over it. Additionally, you can include a small arrow or icon next to the list item to indicate that it's clickable. This will provide a visual cue to users that the item can be interacted with. What do you think?

**Review by Pratiyushkumar — DISMISSED** [review]

**Review by sahsisunny — COMMENTED** [review]
Can you change the color of the button of modal? It it's not match the theme of the status site.

**Comment by sahsisunny** [comment]
Also, add some hover effects to clickable items like underlining the text when it's clickable.
image

**Comment by fakhruddinkw** [comment]
> > What do you suggest?
> 
> I suggest adding a subtle hover effect to the list item, such as changing its background color or underlining the text when someone hovers their mouse pointer over it. This will provide a visual cue to users that the item can be interacted with. What do you think?

Great suggestion, Thank you! I will implement this

**Review by iamitprakash — APPROVED** [review]

**Review by Pratiyushkumar — APPROVED** [review]

**Review by sahsisunny — APPROVED** [review]

**Pull request merged**
