### PR TITLE
Change task status to DONE and UNASSIGNED

### PR DESCRIPTION
**Pull request by chandrareddy7**
### Issue: #800
As `AVAILABLE` and `COMPLETED` task status are being depreciated and `UNASSIGNED` and `DONE` are to be added to status site. When `UNASSIGNED` or `DONE` is clicked we'll retrieve tasks with status `UNASSIGNED` or `DONE` respectively.
This is under feature flag.

### Description:
- Changes are made to retrieve tasks with status `UNASSIGNED` when `UNASSIGNED` is clicked.
- Changes are made to retrieve tasks with status `DONE` when `DONE` is clicked.

### Dev Tested:
- [x] Yes

image
image
image
image

### Test coverage:
image
image
image
image
image

### Currently: 

https://github.com/Real-Dev-Squad/website-status/assets/77037622/01f2989b-b24f-491f-a621-f099b1cb5047

### After Changes:

https://github.com/Real-Dev-Squad/website-status/assets/77037622/6ad96d98-8dd6-419a-9d56-5d0953b72e1e

### Follow-up Issues:
https://github.com/Real-Dev-Squad/website-my/issues/468

### CODE REVIEW

**Comment by sahsisunny** [comment]
It depends on the backend changes I think can you confirm it?

**Comment by sahsisunny** [comment]
Also, add the test coverage stats.

**Comment by chandrareddy7** [comment]
> It depends on the backend changes I think can you confirm it?

Yes, this PR will be changing it.
https://github.com/Real-Dev-Squad/website-backend/pull/1328

**Review by lakshayman — DISMISSED** [review]
Looks good to me

**Review by poornima-alugubelly — APPROVED** [review]

**Review by fakhruddinkw — APPROVED** [review]

**Pull request closed without merging**
