### PR TITLE
Refactor: Migrate Issues, Tasks API to RTK query

### PR DESCRIPTION
**Pull request by bharati-21**
### Issue:
Refactor: Migrate issues, tasks API to RTK query

### Description:
- This PR closes the [issue 156](https://github.com/Real-Dev-Squad/todo-action-items/issues/156) and implements existing API calls for: `GET /issues`, `GET /tasks`, `POST /tasks` and `PATCH /tasks/:id` to RTK query.
- Test cases for `useQuery` and `useMigration` API services for task and issues.
  
### Dev Tested:
- [x] Yes

### Images/video of the change:
- N/A changes only in the code. The functionality for the one-click remains same

### CODE REVIEW

**Review by shubhamsigdar1 — COMMENTED** [review]
Great work @bharati-21

**Review by bhtibrewal — DISMISSED** [review]
Looks okay to me - nice work testing all the cases
just have one thought, we could have initially broken down the task into separate smaller PRs - we could write the queries and test in one PR and then do the implementation part in another, which would help the reviewer

**Review by pallabez — APPROVED** [review]
LGTM. Thanks for the test cases

**Review by pallabez — APPROVED** [review]
Re approving

**Pull request closed without merging**
