### PR TITLE
Add drop down for superuser edit mode

### PR DESCRIPTION
**Pull request by prakashchoudhary07**
Issue link: #481 

Provide dropdown for superuser to edit task status

##### Before:

image

##### After:

image

image

### CODE REVIEW

**Review by RitikJaiswal75 — COMMENTED** [review]
arent we missing tests here?

**Comment by RitikJaiswal75** [comment]
Do we need superuser doing all the status changes, I think assigned, done and unassigned would suffice for superuser. other status changes can be done by developers themselves.

**Comment by prakashchoudhary07** [comment]
> arent we missing tests here?

New PR 😆 
https://github.com/Real-Dev-Squad/website-status/issues/639

**Comment by prakashchoudhary07** [comment]
> Do we need superuser doing all the status changes, I think assigned, done and unassigned would suffice for superuser. other status changes can be done by developers themselves.

Superuser should have the option to change all of it, I think. 
Most of the status will be automated in future

We can discuss about this with the super user and, later change if they tell reduce it

**Review by RitikJaiswal75 — APPROVED** [review]

**Pull request merged**
