### PR TITLE
dev to main sync

### PR DESCRIPTION
**Pull request by shubhamsigdar1**
Date:
Developer Name:

PR Number(s):-
Issue Ticket Number:-

Backend changes
Yes
No

Frontend Changes
Yes
No

Database changes
Yes
No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Yes
No

Deployment notes
Any special instructions for the deployment

Tested in staging
Yes
No

List of PRs going in this Sync.

Also attach their screenshots.

### CODE REVIEW

**Comment by skt17** [comment]
Date: 10-10-2023
Developer Name: Srinath Kumar Tripathy

PR Number(s):- https://github.com/Real-Dev-Squad/website-status/pull/922
Issue Ticket Number:-  https://github.com/Real-Dev-Squad/website-status/issues/916

Backend changes
No

Frontend Changes
Yes


Database changes
No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
No

Deployment notes
Any special instructions for the deployment

Tested in staging
Yes


https://github.com/Real-Dev-Squad/website-status/assets/40158457/574e6326-bf5a-439e-920d-aa152bd87204


List of PRs going in this Sync.

Also attach their screenshots.

**Review by sahsisunny — CHANGES_REQUESTED** [review]
Add the developers name, PR, issue ticket and screenshot of features.

**Comment by aneenajohn** [comment]
Date: 10-10-2023
Developer Name: Aneena

PR Number(s):- 
- https://github.com/Real-Dev-Squad/website-status/pull/880
- https://github.com/Real-Dev-Squad/website-status/pull/930

Issue Ticket Number:- 
For issues - #928 #866  

Backend changes
No

Frontend Changes
Yes

Database changes
No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
No

Deployment notes
Any special instructions for the deployment

Tested in staging
Yes

Reference Video:
https://github.com/Real-Dev-Squad/website-status/assets/75213145/4e60b5fa-c7be-4e7c-aa13-5d4d0e265ac3

**Review by iamitprakash — CHANGES_REQUESTED** [review]
please resolve conflict too

**Review by iamitprakash — DISMISSED** [review]

**Review by Achintya-Chatterjee — DISMISSED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]
LGTM

**Review by anishpawaskar — DISMISSED** [review]

**Comment by aneenajohn** [comment]
> Add the developers name, PR, issue ticket and screenshot of features.

Done

**Review by shubhamsigdar1 — COMMENTED** [review]
LGTM

**Comment by ajoykumardas12** [comment]
### Developer Name:
@ajoykumardas12 

### PR Number(s):-
- #935 

### Backend changes
No

### Frontend Changes
Yes

### Is Under Feature Flag 
Yes

### Database changes
No

### Breaking changes
No

### Deployment notes
NA

### Tested in staging
Yes

### Staging Video:

https://github.com/Real-Dev-Squad/website-status/assets/87164140/f66f050e-4a93-4751-be63-53cbe850981f

**Review by shubhamsigdar1 — COMMENTED** [review]
LGTM

**Pull request merged**
