### PR TITLE
Sync Dev to main

### PR DESCRIPTION
**Pull request by Pratiyushkumar**
Date: 08/07/2023
Developer Name: Pratiyush

PR Number(s):- https://github.com/Real-Dev-Squad/website-status/pull/518
Issue Ticket Number:- https://github.com/Real-Dev-Squad/website-status/issues/486

Backend changes
No

Frontend Changes
Yes

Database changes
No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
https://github.com/Real-Dev-Squad/website-status/issues/604

Deployment notes
NA

Tested in staging
Yes

List of PRs going in this Sync.

- #631 
- #632 
- #518 
- #636
- #622 
- #638 
- #655

Also attach their screenshots.
image

image

https://github.com/Real-Dev-Squad/website-status/assets/82165483/ba6cc2d4-d29a-4178-aac2-e5f4a9d1625b

https://github.com/Real-Dev-Squad/website-status/assets/53934353/e3ac9266-c47e-4e77-9056-3ea3254e00a6

### CODE REVIEW

**Comment by RitikJaiswal75** [comment]
Thank you for the video, As I can see once the progress is submitted the missed updates count does not change until refreshed,
also even after submitting my standup why does it show 1 missed update?

Please create an issue ticket mentioning both assign them to yourself and then link them here.

**Comment by Pratiyushkumar** [comment]
> Thank you for the video, As I can see once the progress is submitted the missed updates count does not change until refreshed, also even after submitting my standup why does it show 1 missed update?
> 
> Please create an issue ticket mentioning both assign them to yourself and then link them here.

Here is the issue ticket - https://github.com/Real-Dev-Squad/website-status/issues/653

**Comment by j24m** [comment]
> Thank you for the video, As I can see once the progress is submitted the missed updates count does not change until refreshed, also even after submitting my standup why does it show 1 missed update?

- #655
https://github.com/Real-Dev-Squad/website-status/assets/53934353/c2367299-9532-49d5-bcd5-a44b3d5c7a08

**Comment by j24m** [comment]
> Thank you for the video, As I can see once the progress is submitted the missed updates count does not change until refreshed, also even after submitting my standup why does it show 1 missed update?

> Please create an issue ticket mentioning both assign them to yourself and then link them here.


PR : 
- #655 

https://github.com/Real-Dev-Squad/website-status/assets/53934353/fea4ed76-dd5a-4962-8068-29216a0df801

**Pull request merged**
