### PR TITLE
Fix/prettier and add prettier check in github workflow

### PR DESCRIPTION
**Pull request by sahsisunny**
- [x] Fix Format style using prettier
- [x] Add check for prettier in GitHub workflow

### CODE REVIEW

**Review by bhtibrewal — CHANGES_REQUESTED** [review]
This PR has changes of this PR #473  in this one, please fix it first

**Comment by sahsisunny** [comment]
> This PR has changes of this PR #473 in this one, please fix it first

where ? I am not able to see the changes from #473 in this PR

**Review by Pratiyushkumar — COMMENTED** [review]
Have you made changes to 17 files, these much files cannot be reviewed. Please check if there is any unnecessary changes being moved

**Comment by sahsisunny** [comment]
> Have you made changes to 17 files, these much files cannot be reviewed. Please check if there is any unnecessary changes being moved

See the number of line changes not files. Btw only prettier changes made nothing extra.

**Comment by sahsisunny** [comment]
> Have you made changes to 17 files, these much files cannot be reviewed. Please check if there is any unnecessary changes being moved

You are saying that it is not possible to review this PR?

**Comment by sahsisunny** [comment]
> Have you made changes to 17 files, these much files cannot be reviewed. Please check if there is any unnecessary changes being moved

You are saying that it is not possible to review this PR?

**Review by Pratiyushkumar — CHANGES_REQUESTED** [review]
if only a prettier file is changed then why are you  sending extra files in PR
please see bhavika's comments

**Comment by sahsisunny** [comment]
> if only a prettier file is changed then why are you  sending extra files in PR
> please see bhavika's comments

Where? Can you comment on the line which was added?

**Review by Pratiyushkumar — APPROVED** [review]
It was my mistake, I got confused.
the prettier change looks good to me.

**Review by bhtibrewal — APPROVED** [review]
okay to merge

**Pull request merged**
