### PR TITLE
Fixed css in mobile view of task details page

### PR DESCRIPTION
**Pull request by ankitbajpai65**
### Description:
Fixed CSS of the task details page and made it responsive for mobile.

### Images/video of the change:

image
image
https://github.com/Real-Dev-Squad/website-status/assets/85179394/f3e57416-7618-4c76-90db-528303ad4a8c

### CODE REVIEW

**Review by Pratiyushkumar — COMMENTED** [review]
Please add a screen video recording for reference.

**Review by kotesh-arya — COMMENTED** [review]
It would be helpful to review, if you share the Screenshots of initial state too, so that It will be easily compared with the fixed version 👍🏻

**Comment by ankitbajpai65** [comment]
> Please add a screen video recording for reference.

I attached the video recording after the changes. Please find the link above.

**Comment by ankitbajpai65** [comment]
> It would be helpful to review, if you share the Screenshots of initial state too, so that It will be easily compared with the fixed version 👍🏻

@kotesh-arya @Pratiyushkumar 
Here are screenshots of the initial state (before the changes) - 
image
image
image

Please find the screenshots and video recording after the changes provided above
Let me know for anymore requirement.

**Review by kotesh-arya — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Pull request merged**
