### PR TITLE
Fix loader in availability panel

### LINKED ISSUE #202: Fix loader for Availability panel
FO: @Pavangbhat 
Issue :- No tasks found is displayed for a while before tasks get render :point_down: 
https://user-images.githubusercontent.com/45538392/134010105-f8eb960f-55f2-4663-9966-7adbc9969f0b.mp4

### PR DESCRIPTION
**Pull request by shubham-y**
Fixes #202

### CODE REVIEW

**Review by Pavangbhat — CHANGES_REQUESTED** [review]
Hey, @shubham-y looks like your changes have not solved the problem. You can check if the changes you make is working or not by slowing the network request in the browser 
This might help https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling

**Comment by shubham-y** [comment]
Hey, @Pavangbhat it worked fine in my local setup. I have attached a video with the Regular 2G option for your review
[https://user-images.githubusercontent.com/46373689/135764723-b37797bd-7b2b-45d6-a07b-bfb78e58dabb.mp4](https://user-images.githubusercontent.com/46373689/135764723-b37797bd-7b2b-45d6-a07b-bfb78e58dabb.mp4)

**Comment by Pavangbhat** [comment]
> Hey, @Pavangbhat it worked fine in my local setup. I have attached a video with the Regular 2G option for your review
> [https://user-images.githubusercontent.com/46373689/135764723-b37797bd-7b2b-45d6-a07b-bfb78e58dabb.mp4](https://user-images.githubusercontent.com/46373689/135764723-b37797bd-7b2b-45d6-a07b-bfb78e58dabb.mp4)
> 
> 

Okay I will try it once more on my system

**Review by Pavangbhat — APPROVED** [review]
Looks Good to me, great work :tada:

**Review by whyDontI — APPROVED** [review]

**Pull request merged**
