### PR TITLE
Dev to main Sync

### PR DESCRIPTION
**Pull request by RitikJaiswal75**
### **PRs in this sync:**
- #880 
- #913 
- #915 

### Developers:
@aneenajohn @RitikJaiswal75 @ajoykumardas12 

PR #913 reverts a previous PR(#908 ).

### CODE REVIEW

**Comment by ajoykumardas12** [comment]
PR No:
- #915

Changes of PR #915 are tested and working fine.
- Multiple Assignee Tasks Search
- TasksContents Component Refactor
- Disabled spellCheck on search input box

Video of Changes:

https://github.com/Real-Dev-Squad/website-status/assets/87164140/8a1d2795-81a2-4623-b682-ddf7bd2e1831

**Comment by aneenajohn** [comment]
> ### **PRs in this sync:**
> * [Fix for UI Breaking Issue on Status Page for Smaller Devices and Tablets #880](https://github.com/Real-Dev-Squad/website-status/pull/880)
> * [Revert "Remove Feature Flag | Assign Issue" #913](https://github.com/Real-Dev-Squad/website-status/pull/913)
> * [Multiple Assignee Tasks Search and TasksContent Component Refactor #915](https://github.com/Real-Dev-Squad/website-status/pull/915)
> 
> ### Developers:
> @aneenajohn @RitikJaiswal75 @ajoykumardas12
> 
> PR #913 reverts a previous PR(#908 ).

@ajoykumardas12 PR #880 is for fixing the responsiveness of tasks page, It is good to go as well.

**Comment by vinit717** [comment]
what about other pr staging proof?

**Comment by ajoykumardas12** [comment]
@aneenajohn Please add video of staging env

**Comment by ajoykumardas12** [comment]
> what about other pr staging proof?

@RitikJaiswal75 said he won't need to add something for PR #913 as it's a revert PR only. https://discord.com/channels/673083527624916993/1007355818603192360/1160790160720543825

**Review by vinit717 — APPROVED** [review]

**Pull request merged**
