### PR TITLE
Fix for the issue: GitHub issue link is to be displayed on the task details page.

### PR DESCRIPTION
**Pull request by kapillondhe**
### Description:
Changes in src/components/issues/Card.tsx will send html_url of GitHub issue for task creation. Backend changes will store this html_url in the task database.

Changes in src/components/taskDetails will display the "Open git issue" button in task details page.

### Anything you would like to inform the reviewer about:
Both frontend and backend changes are required. PR created for website-backend #1383.

### Dev Tested:
- [ ✓] Yes

### Images/video of the change:
image

### Follow-up Issues (if any)
No.

### CODE REVIEW

**Comment by sahsisunny** [comment]
> image

## UI does not look good to me

**Review by sahsisunny — CHANGES_REQUESTED** [review]
Also write the test please

**Review by vinit717 — COMMENTED** [review]
please resolve merge conflict first

**Comment by kapillondhe** [comment]
> UI does not look good to me

I appreciate your feedback. To help me improve the UI, could you please provide more details about what aspects of the UI you find unsatisfactory?

**Comment by kapillondhe** [comment]
> > image
> 
> ## UI does not look good to me

Added the "Open new tab" icon beside git icon. Hope this looks good. Please let me know if there is any specific requirement.

image

**Comment by kapillondhe** [comment]
> Also write the test please

Tests added. Thanks.

**Comment by kapillondhe** [comment]
PR #827 raised.

**Pull request closed without merging**
